### ISSUE TITLE
Nway logging/output in case of success

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/ophys_nway_matching#36]
Tasks:
- [x] Agree on data structure to do this
- [x] Add the red/green plot shown below as an output of successful nway matching.
- [x] Add the pandas dataframe pairwise count/fraction plot shown below as an output of successful nway matching.
- [x] bump version
- [x] Implement in pipeline
- [x] Use this to generate plots for QC-a-thon 12/10

Background:
In working on [#1506](https://app.zenhub.com/workspaces/allensdk-10-5c17f74db59cfb36f158db8c/issues/alleninstitute/allensdk/1506), Marina expressed desire to have qc plots generated by the ophys_nway cell matching code automatically.

One example was this plot, which she uses to visually check registration:
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/395a0598-f119-4f4f-9733-f7a5a2fdeb96)

I had made a version of this, [prototype code here](https://github.com/AllenInstitute/ophys_nway_matching/blob/feature/summary_plots/nway/plot_overlaps.py)
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/c71c589a-dbb0-47a8-957e-9ae4de47a433)

She pointed me to a directory with types of plots:
```
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/overlay_images_grid/container_1018027567.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/matched_cells_exp_pairs/container_1018027567.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/segmentation_valid_invalid/container_1018027567.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/fraction_matched_cells/container_1018027567.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/registration_overlays/container_1018027567_0.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/registration_overlays/container_1018027567_1.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/registration_images/container_1018027567.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567_registration_images.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567_registration_overlays_0.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567_matched_cells_exp_pairs.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567overlay_images_grid.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567_segmentation_valid_invalid.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567_fraction_matched_cells.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567_registration_overlays_1.png
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/cell_matching_validation/all/1018027567_matched_cells_exp_pairs_valid_only.png
```

**Comment by wbwakeman** [comment]
Need to understand which of these plots is a priority, and how important it is relative to other work.

**Comment by djkapner** [comment]
@matchings 
Can you post in this issue a link to your code that generates the R/G plots?
I think what you want here is 1 plot per container like:
<img src="https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/6a1d8f07-042b-4322-b08c-feab463d0891" width=400>

and one plot per container like:
<img src="https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/180bc8c1-0250-4917-8fdf-f09070617edb" width=400>

Since they are both symmetric with redundant information, I propose combining them into 1 plot that is output per nway run.

**Comment by matchings** [comment]
yes i will provide the code shortly. i like your idea of combining them into one plot! 

one point relevant to these summary plots - it would be useful to have both the experiment_ids of the matched pairs, and the 'session_type' (or maybe its called 'session_name') in the plot. the experiment_ids are needed to know where to look deeper for issues, and the session type is useful to include because there are biological reasons for some session pairs to have different fraction matched cells than others. For example, matching two sessions with image set A would typically give more matches than matching sessions with two different image sets (since cells respond to different images and some may not show up in both sessions). Also the RF mapping session is very different than behavior sessions and also would be expected to have fewer matches due to differences in activity profiles.

**Comment by djkapner** [comment]
great, @njmei and I were discussing experiment id vs. stimulus name just this morning. (and this code)

**Comment by matchings** [comment]
Here is the code to generate the plots above:
 https://github.com/AllenInstitute/visual_behavior_analysis/blob/dev/notebooks/201109_cell_matching_qc_plots.ipynb

**Comment by djkapner** [comment]
I think we have 3 versions of code to make similar plots:
[Marina's](https://github.com/AllenInstitute/visual_behavior_analysis/blob/dev/notebooks/201109_cell_matching_qc_plots.ipynb) (which is the look-and-feel we are going for)
[Nick's](https://gist.github.com/njmei/c53a10b06ea646c18b1e042b1aa283c6)
[mine](https://github.com/AllenInstitute/ophys_nway_matching/blob/feature/summary_plots/nway/plot_overlaps.py)

@njmei your's is just a gist, right, you don't have a special branch?

**Comment by njmei** [comment]
@djkapner Correct, just a gist.
