### ISSUE TITLE
Nway logging/output in case of failure.

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/ophys_nway_matching#56]
After improving registration, there are a few things to add to nway output/logging to help establish the cause of a failure.
This issue is about logging and output in the case of a failure.
#36 is about logging/plotting/output in the case of success.

Tasks:
- [x] Modify flow so that pairwise failure ("Identity") only raises exception after all pairs are done.
- [x] Log a boolean (1/0) table of the pairwise matches, indicating registration success or failure ("Identity") for a given pair. This will provide a quick look to indicate whether one particular experiment is the culprit.
- [x] In the event that a registration pair fails, output a plot like this, and log the path, for an easy assessment of the data quality:
<img src="https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/5797e9cf-40c7-46b7-9476-db35e1f22777" alt="drawing" width="400"/>
 - [ ] Establish with @matchings a good way to proceed with nway in the event of 1 experiment failing. For example:
    Option 1: If 1 experiment fails every registration attempt, automatically eliminate it from the nway attempt, and let nway proceed. But, how to raise the issue that this experiment is bad?
    Option 2: Fail the nway job entirely, but with sufficient logging to indicate a bad experiment. @wbwakeman can you pelase add a comment about how we "fail an experiment"?

**Comment by wbwakeman** [comment]
![image.png](https://images.zenhubusercontent.com/5c4b4c0003b3e817859aa406/5be026c0-2ee1-41e0-a893-7852a154c885)
Nway cell matching will include all experiments in the container that have the workflow state 'qc' or 'passed'.  To fail an ophys_experiment, go to http://lims2/ophys_experiments .  Click on the 'fail' link for the experiment.
