### ISSUE TITLE
QC-a-thon data survey

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/ophys_nway_matching#57]
Tasks:
- [x] @wbwakeman or @matchings can you please post the SQL query or VBA call to get the ~240 containers expected for visual behavior release and QC-a-thon review?
- [x]  after #36 and #56 (and perhaps anything else I haven't yet covered) rerun the above containers.
- [x] collect 3 types of success plots and place in isilon location readable by Doug's QC webapp. Update his yml that describes them.
- [x] For all successes: review the QC output plots, probably with @matchings to look for any false successes. Things to evaluate and summarize (we may in this process establish some numerical thresholds to codify):
    * SSIM before/after registration per-pair.
    * fraction of cells matched per pair.
    * translation [pixels in x,y] applied by registration.
    * an absolute measure of registration ? (I am not sure what this would be right now. Suggestion was SSIM, but the absolute value is dependent on images, so I'm not sure this is a good metric)
- [ ] evaluation of metrics in relation to simultaneously recorded planes (in platform.json?)
- [x] For all failures, establish cause of failure, if possible, and add to a log for science team to review during QC-a-thon.

**Comment by wbwakeman** [comment]
The ids of the candidate containers that I am aware of are listed here: https://gist.github.com/wbwakeman/f3a14e1e7bc92f4f829453de4d01e359

They are broken into containers that have failed nway cell matching (21) and succeeded (250)

**Comment by matchings** [comment]
documenting some desired information relevant to nway QC: 

it would be great if the translation values and other metrics could be saved out into a master file somewhere (preferably easily loaded as a pandas dataframe) with information for all processed experiments that contained the container ID, each experiment ID in the registration pair, the translation values, and any / all other metrics that are included in the json files, or can be computed from the json files, such as the number of matched cells, number of total cells, fraction matched cells, SSIM values pre and post registration, etc.

alternatively, providing a simple function to get this information for a given container would allow the science team to compile and do the analysis ourselves.

the main barrier is that we (scientists) are not super familiar with json and it unfortunately takes quite a bit of parsing and interpretation for us to extract the relevant information systematically. i could probably figure it all out in a week or so of work, but i imagine it would take Dan a day or less to write a function to get the relevant numbers into a dataframe format.

**Comment by djkapner** [comment]
Failure log for 21/271 container failures in NWAY cell matching queue:
https://alleninstitute-my.sharepoint.com/:x:/g/personal/danielk_alleninstitute_org/ER1dI09eGbhKmtadJrHGWZEBclDWXB2kM_tgwJuXHITEog?e=3efJnw
marina may copy elsewhere

**Comment by djkapner** [comment]
I created 250 x3 symlinks to successful container plots in these directories:
```
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/container_plots/nway_warp_overlay_plot
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/container_plots/nway_warp_summary_plot
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/container_plots/nway_match_fraction_plot
```
and updated Doug's web app yml to include:
```
Nway Production Match Fraction: nway_match_fraction_plot
Nway Production Warp Overlay: nway_warp_overlay_plot
Nway Production Warp Summary: nway_warp_summary_plot
```
`/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/container_plots/plot_definitions.yml`

I did this with the following script:
```
import lims.query_utils as qu
from pathlib import Path
import json
import re
import os

def get_plot_paths(storage_dir: Path):
    outputs = list(storage_dir.rglob("*ophys_cell_matching_output.json"))
    if len(outputs) != 1:
        raise ValueError(f"multiple output files for {storage_dir}")
    with open(outputs[0], "r") as f:
        outj = json.load(f)
    for k in list(outj.keys()):
        if "_plot" not in k:
            outj.pop(k)
    return outj

def symlink_plots(outj, root_destdir):
    for k, v in outj.items():
        tmpstr = re.findall("experiment_container_\d+", v)[0]
        cid = re.findall("\d+", tmpstr)[0]
        dst = root_destdir / k / f"container_{cid}.png"
        try:
            os.symlink(v, dst)
        except FileExistsError:
            pass

qstring = """
SELECT j.job_state_id, j.completed_at, j.enqueued_at, jq.name AS jq, vbec.id AS vbec_id, vbec.workflow_state, vbec.allow_cell_specimen_update, j.id AS j_id, vbcr.storage_directory
FROM visual_behavior_experiment_containers vbec
JOIN Jobs j ON j.enqueued_object_id=vbec.id AND j.archived = 'f'
JOIN job_queues jq ON jq.id=j.job_queue_id AND jq.name = 'OPHYS_NWAY_CELL_MATCHING_QUEUE'
JOIN visual_behavior_container_runs vbcr ON vbcr.visual_behavior_experiment_container_id = vbec.id AND vbcr.current = 't' AND vbcr.job_strategy_class = 'OphysNwayCellMatchingStrategy'
WHERE
vbec.id IN ({})
"""

success_ids = [791352433, 803516615, 803517529, 803589437, 814796612, 814797528, 825183217, 829561794, 843049827, 845588020, 846213087, 846215539, 848390542, 863992815, 869781307, 876461613, 876693090, 876693136, 890047007, 895259496, 896318095, 902748564, 902748650, 906963896, 911248946, 915584942, 928325203, 929913236, 930022332, 930024022, 939523510, 941373529, 947838486, 957024596, 957361481, 957366099, 957570596, 968451510, 969421516, 975371413, 978206330, 989461845, 991913064, 991913246, 991913453, 999191979, 1000740410, 1000740620, 1006071814, 1006386845, 1018027543, 1018027546, 1018027549, 1018027552, 1018027555, 1018027558, 1018027561, 1018027564, 1018027593, 1018027599, 1018027602, 1018027605, 1018027608, 1018027611, 1018027615, 1018027647, 1018027650, 1018027654, 1018027657, 1018027660, 1018027663, 1018027666, 1018027721, 1018027724, 1018027727, 1018027730, 1018027733, 1018027737, 1018027740, 1018027744, 1018027747, 1018027750, 1018027753, 1018027756, 1018027759, 1018027762, 1018027765, 1018027768, 1018027772, 1018027775, 1018027778, 1018027784, 1018027787, 1018027790, 1018027796, 1018027799, 1018027802, 1018027806, 1018027809, 1018027813, 1018027816, 1018027819, 1018027822, 1018027825, 1018027828, 1018027831, 1018027834, 1018027837, 1018027841, 1018027844, 1018027847, 1018027853, 1018027859, 1018027862, 1018027865, 1018027868, 1018027874, 1018027878, 1018027890, 1018027936, 1018027939, 1018027942, 1018027945, 1018027948, 1018027951, 1018027954, 1018027957, 1018027962, 1018027965, 1018027968, 1018027971, 1018027974, 1018027981, 1018028018, 1018028021, 1018028025, 1018028028, 1018028031, 1018028034, 1018028037, 1018028040, 1018028046, 1018028049, 1018028052, 1018028055, 1018028058, 1018028061, 1018028064, 1018028067, 1018028135, 1018028138, 1018028141, 1018028144, 1018028147, 1018028150, 1018028153, 1018028156, 1018028166, 1018028169, 1018028172, 1018028176, 1018028179, 1018028182, 1018028185, 1018028188, 1018028196, 1018028199, 1018028202, 1018028206, 1018028209, 1018028212, 1018028215, 1018028218, 1018028254, 1018028261, 1018028267, 1018028273, 1018028339, 1018028342, 1018028345, 1018028348, 1018028351, 1018028354, 1018028357, 1018028360, 1018028364, 1018028367, 1018028370, 1018028374, 1018028377, 1018028380, 1018028383, 1018028387, 1018028390, 1018028393, 1018028396, 1018028399, 1018028402, 1018028405, 1018028408, 1018028411, 1018028423, 1018028426, 1018028429, 1018028432, 1018028435, 1018028438, 1018028445, 1018058743, 1018058747, 1018058751, 1018058755, 1022731524, 1022731527, 1022731531, 1022731534, 1022731537, 1022731540, 1022731544, 1022731547, 1022733783, 1022733786, 1022733792, 1022733798, 1022733801, 1022733804, 1026722858, 1026722870, 1026722876, 1036303886, 1037672782, 1037672785, 1037672789, 1037672795, 1037672798, 1037672805, 1039579201, 1040782478, 1045477185, 1046279796, 1046576781, 1046576784, 1046576787, 1046576791, 1046576794, 1049224697, 1051327176, 1052096566, 1052096570, 1052096573]

creds = qu.get_db_credentials()
conn = qu.DbConnection(**creds)

idstr = ",".join([str(i) for i in success_ids])
results = conn.query(qstring.format(idstr))

outjs = [get_plot_paths(Path(r['storage_directory'])) for r in results]

root_destdir = Path("/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/container_plots")

for outj in outjs:
    symlink_plots(outj, root_destdir)
```

**Comment by djkapner** [comment]
I made a notebook for calculating a dataframe of all of these metrics and saved to csv. The notebook and dataframe are:
```
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/qc_notebooks/nway_results_qc_2020-Dec.csv
\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\qc_notebooks\nway_results_qc_2020-Dec.csv
/allen/programs/braintv/workgroups/nc-ophys/visual_behavior/qc_plots/qc_notebooks/2020-Dec-QC-a-thon-nway.ipynb
\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\qc_notebooks\2020-Dec-QC-a-thon-nway.ipynb
```

**Comment by djkapner** [comment]
above dataframe was updated further:
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/1e9c5a22-0215-4c38-9f33-a045d9947798)
